### ISSUE TITLE
Does hk support wayland ?

### ISSUE THREAD

**Issue by jrbalderrama** [ltratt/hk#1]
After your post about debugging ``Debugging A Failing Hotkey´´ I tried to install `hk` but I got some errors during compilation. I checked the code and I realize that you use X11 lib. Before going further I would like to check if Wayland is supported.

**Comment by ltratt** [comment]
As of now, hk is X11 only. I'm open to wayland support, but I don't use wayland so someone else will have to do the hard yards there I'm afraid!
